name: simplytranslate_mobile
description: An alternative frontend to Google Translate

publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  get_storage: ^2.0.3
  audioplayers: ^4.0.1
  package_info_plus: ^4.0.1
  url_launcher: ^6.0.12
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  path_provider: ^2.0.8
  permission_handler: ^10.2.0
  html: ^0.15.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ca/
    - assets/settings/
  generate: true

flutter_intl:
  enabled: true
  class_name: L10n
  